### ISSUE TITLE
weewx-influx.tgz

### ISSUE THREAD

**Issue by 4noxx** [matthewwall/weewx-influx#15]
you write:

1) run the installer:

wee_extension --install weewx-influx.tgz

where can i find the tgz file?

**Comment by 4noxx** [comment]
zip install seems wrong

wee_extension --install weewx-influx-master.zip
Request to install 'weewx-influx-master.zip'
Extracting from zip archive weewx-influx-master.zip
Saving installer file to /usr/share/weewx/user/installer/influx
Saved configuration dictionary. Backup copy at /etc/weewx/weewx.conf.20180124181938
Finished installing extension 'weewx-influx-master.zip'
root@orangepiplus:/home/ralf/weewx-influx-master# cd /usr/share/weewx/user/installer/influx
root@orangepiplus:/usr/share/weewx/user/installer/influx# ls
install.py
root@orangepiplus:/usr/share/weewx/user/installer/influx# sudo chmod +x *.*
root@orangepiplus:/usr/share/weewx/user/installer/influx# ls
install.py
root@orangepiplus:/usr/share/weewx/user/installer/influx# ./install.py
from: can't read /var/mail/setup
./install.py: line 7: syntax error near unexpected token `('
./install.py: line 7: `def loader():'
root@orangepiplus:/usr/share/weewx/user/installer/influx#

**Comment by steffenschumacher** [comment]
I also don't get this - the zip now seems gone, and I suspect we need to RTFM to figure out how to manually install weewx modules, in order to use this..

**Comment by matthewwall** [comment]
the wee_extension utility will install from a source tree or from a .tgz or a .zip

for example, any of  these will work:
```
wee_extension --install /path/to/weewx-influx.tgz

wee_extension --install /path/to/weewx-influx.zip

wee_extension --install /path/to/weewx-influx
```

**Comment by steffenschumacher** [comment]
Thanks - managed to install it by hand..
