### ISSUE TITLE
Change log level option

### ISSUE THREAD

**Issue by mdallaire** [matthewwall/weewx-influx#20]
I am using the weewx-influx plugin with the "loop" binding. This obviously generate a lot of post data.

When trying to look at the log it is currently filled with  "restx: Influx: Published record ..." every one or two seconds.

An option to change the log level for the plugin to only display errors or warning would be a nice to have.

This would also be nice to have on the mqtt plugin.

My weewx.conf file currently have "debug = 0"

**Comment by matthewwall** [comment]
these already exist and apply to every restful service:
```
log_success
log_failure
```
just set `log_success=false` in `[StdRESTful]` or in the `[Influx]` section if you only want it to apply to the influx uploader.
