### ISSUE TITLE
tgz?

### ISSUE THREAD

**Issue by johnny2678** [matthewwall/weewx-influx#3]
Happy I found this - confused about step 1 - should we clone the repo and then tar/gzip all files into a tgz?

**Comment by matthewwall** [comment]
you can install from tgz, zip, or raw directory.  for example:

wget https://github.com/matthewwall/weewx-influx/archive/master.zip -O weewx-influx.zip
wee_extension --install weewx-influx.zip

OR

git clone https://github.com/matthewwall/weewx-influx
wee_extension --install weewx-influx

**Comment by johnny2678** [comment]
Perfect - thx.
