### ISSUE TITLE
Influx User need admin rights

### ISSUE THREAD

**Issue by Hofei90** [matthewwall/weewx-influx#7]
Hi,
when the influx user dont have admin rights, then isn't possible to run the skript.

influx.py:
In Line 281 whould create a database, that need admin rights, i think it s better that the skript don't create any database's and so the influx user don't need admin rights.

**Comment by matthewwall** [comment]
fixed at commit 19d98ba

specify dbadmin_username and dbadmin_password to use separate credentials for creating database.  and the extension no long fails if it cannot create database.

**Comment by Hofei90** [comment]
after the installation the new Version from commit 19d98ba, i have this error:

`Jul 23 16:14:32 wetterstation weewx[1038]:     ****  __init__() got an unexpected keyword argument 'dbadmin_username'
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  Traceback (most recent call last):
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 865, in main
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      engine = engine_class(config_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 77, in __init__
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.loadServices(config_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 141, in loadServices
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/user/influx.py", line 241, in __init__
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.archive_thread = InfluxThread(self.archive_queue, **site_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  TypeError: __init__() got an unexpected keyword argument 'dbadmin_username'
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  Exiting.
`
