### ISSUE TITLE
unexpected keyword argument 'dbadmin_username'

### ISSUE THREAD

**Issue by Hofei90** [matthewwall/weewx-influx#8]
after the installation the new Version from commit 19d98ba, i have this error:

Jul 23 16:14:32 wetterstation weewx[1038]:     ****  __init__() got an unexpected keyword argument 'dbadmin_username'
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  Traceback (most recent call last):
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 865, in main
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      engine = engine_class(config_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 77, in __init__
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.loadServices(config_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/weewx/engine.py", line 141, in loadServices
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Jul 23 16:14:32 wetterstation weewx[1038]:     ****    File "/usr/share/weewx/user/influx.py", line 241, in __init__
Jul 23 16:14:32 wetterstation weewx[1038]:     ****      self.archive_thread = InfluxThread(self.archive_queue, **site_dict)
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  TypeError: __init__() got an unexpected keyword argument 'dbadmin_username'
Jul 23 16:14:32 wetterstation weewx[1038]:     ****  Exiting.

weewx.conf:
[[Influx]]
        host = ***
        database = ***
        port = 8086
        username = ***
        password = ***
        dbadmin_username = ***
        dbadmin_password = ***
        unit_system = METRIC

**Comment by matthewwall** [comment]
fixed at commit 79692b4
