### ISSUE TITLE
problem using influx plugin: global name 'un' is not defined

### ISSUE THREAD

**Issue by peters77** [matthewwall/weewx-influx#9]
Hi,

I want to setup the influx export plugin but weewx stops with:

 restx: Influx: service version is 0.6
Aug 14 22:28:10  weewx[19361]: restx: Influx: desired unit system is METRICWX
Aug 14 22:28:10  weewx[19361]: restx: Influx: tags None
Aug 14 22:28:10  weewx[19361]: restx: Influx: database is weewx_metrics
Aug 14 22:28:10  weewx[19361]: engine: Caught unrecoverable exception in engine:
Aug 14 22:28:10 weewx[19361]:     ****  global name 'un' is not defined
Aug 14 22:28:10  weewx[19361]:     ****  Traceback (most recent call last):
Aug 14 22:28:10  weewx[19361]:     ****    File "/usr/share/weewx/weewx/engine.py", line 865, in main
Aug 14 22:28:10  weewx[19361]:     ****      engine = engine_class(config_dict)
Aug 14 22:28:10  weewx[19361]:     ****    File "/usr/share/weewx/weewx/engine.py", line 77, in __init__
Aug 14 22:28:10  weewx[19361]:     ****      self.loadServices(config_dict)
Aug 14 22:28:10  weewx[19361]:     ****    File "/usr/share/weewx/weewx/engine.py", line 141, in loadServices
Aug 14 22:28:10  weewx[19361]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Aug 14 22:28:10 weewx[19361]:     ****    File "/usr/share/weewx/user/influx.py", line 241, in __init__
Aug 14 22:28:10  weewx[19361]:     ****      self.archive_thread = InfluxThread(self.archive_queue, **site_dict)
Aug 14 22:28:10  weewx[19361]:     ****    File "/usr/share/weewx/user/influx.py", line 306, in __init__
Aug 14 22:28:10  weewx[19361]:     ****      if un is not None:
Aug 14 22:28:10  weewx[19361]:     ****  NameError: global name 'un' is not defined
Aug 14 22:28:10 weewx[19361]:     ****  Exiting.

Something goes wrong with user/passwd but no authentication set in the InfluxDB!?

Any idea?

Thanks in advance!

Regards,

Christian

**Comment by matthewwall** [comment]
fixed at commit 1def047
